name: storage_permissions
description: Storage permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check storage  permissions.
version: 4.0.1
authors:
  - Baseflow <hello@baseflow.com>
  - long1eu <home@long1.eu>
  - Sebastian Roth <sebastian.roth@gmail.com>
  - Ramon Cardena <info@ramoncardena.com>

homepage: https://github.com/ramoncardena/flutter-sotrage-permission-handler

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.7.0

flutter:
  plugin:
    androidPackage: com.baseflow.permissionhandler
    pluginClass: PermissionHandlerPlugin
